# Generated by Django 3.1.7 on 2021-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210419_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(default='noimage.png', upload_to='product_image', verbose_name='Изображение подкатегории'),
        ),
    ]
